dist: xenial
sudo: true

language: python
python:
  - 3.6
  - 3.7

install:
  - pip install --upgrade pip setuptools wheel
  - pip install -r requirements.txt
  - pip wheel --no-deps .
  - pip install pydra*.whl

script:
  - py.test -n auto -vs pydra/engine/tests/test_newnode.py
