name: Test Pydra (singularity)

on: [push, pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8]
      fail-fast: False

    steps:
      - name: Set env
        run: |
          echo ::set-env name=RELEASE_VERSION::v3.5.0
      - name: Setup Singularity
        uses: actions/checkout@v2
        with:
          repository: hpcng/singularity
          ref: 'v3.5.0'
          path: 'singularity'
      - name: Setup GO
        uses: actions/setup-go@v2
        with:
          go-version: '^1.13'
      - name: Install OS deps
        run: |
          sudo apt-get update
          sudo apt-get install flawfinder squashfs-tools uuid-dev libuuid1 libffi-dev libssl-dev libssl1.0.0 \
          libarchive-dev libgpgme11-dev libseccomp-dev wget gcc make pkg-config -y
      - name: Build
        run: |
          cd singularity
          ./mconfig --without-suid -p ${{ runner.tool_cache }}/singularity/${{ env.RELEASE_VERSION }}/x64
          make -C ./builddir
          sudo make -C ./builddir install
          cd ..
      - name: Echo singularity version
        run: |
          echo ${{ github.ref }}
          ${{ runner.tool_cache }}/singularity/${{ env.RELEASE_VERSION }}/x64/bin/singularity --version


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Update build tools
        run: python -m pip install --upgrade pip setuptools


      - name: Checkout Pydra repo
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository }}
      - name: Install pydra (test)
        run: pip install -e ".[test]"


      - name: Pytest
        run: pytest -vs --cov pydra --cov-config .coveragerc --cov-report xml:cov.xml --doctest-modules pydra
      - name: Upload to codecov
        run: codecov -f /pydra/cov.xml -F unittests -e GITHUB_WORKFLOW
